### PR TITLE
fix coverage for typescript (karma-remap-coverage)

### PR DESCRIPTION
**Pull request by dvic**

### CODE REVIEW

**Comment by dvic** [comment]
I tested this setup with a few classes and it seems to give correct coverage reports 😃

**Comment by Toilal** [comment]
Thanks ! 

There's still an issue with code typescript coverage due to the  [regexp lying in test/unit/index.ts](https://github.com/Toilal/vue-webpack-template/blob/master/template/test/unit/index.ts#L15) that returns no modules to require

So currently your typescript code coverage only includes source files that are required by your tests, but i'll fix this asap.

(fixed with https://github.com/Toilal/vue-webpack-template/commit/42e242e5a028971dea1afed22dcd91becf5321e4)

**Comment by Toilal** [comment]
Another problem : it displays after running unit tests the following message

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unrecognized report type of "lcov".
```
any idea ?

**Comment by dvic** [comment]
I guess `lcov` is not supported by `karma-remap-coverage` and `remap-istanbul`: https://github.com/SitePen/remap-istanbul/blob/684fb0e88b3673a1563c61b59cf3091f54c1ddae/tests/unit/lib/writeReport.js#L18

So I'd suggest to use only `lcononly` and `html` (by the way: the folder for `html` is currently pointing to `./test/unit/coverage/lcov-report`.

By the way: nice to see that all sources are included now, nice fix! 👍

**Comment by Toilal** [comment]
Yes that's what i've done with last commit : https://github.com/Toilal/vue-webpack-template/commit/f506b513d9cdd43c42c1aa619ebeffa0be3fd9ce

Thank you too for help and engagement :)

**Comment by dvic** [comment]
You are welcome :) 

By the way: did you advertise this project on https://github.com/vuejs/vue-cli/issues/263 ? Others might also like it!

**Comment by Toilal** [comment]
Done thanks :)

I a near future, we could ask for this repository to become an official template hosted at https://github.com/vuejs-templates

**Pull request merged**
